### ISSUE TITLE
pre-trained models

### ISSUE THREAD

**Issue by loretoparisi** [artetxem/monoses#1]
Hello @artetxem thank you for this work! 💯 🥇 
Do you have any pre-trained model (dummy or not) in order to check the decoding before starting a new training from scratch?
Thanks a lot!

**Comment by artetxem** [comment]
I do, but the full models are too big to share (~11GB per language model + ~5GB for each probing table). Moreover, the underlying moses.ini files use absolute paths and you would have to change them manually.

If you just want a dummy model, you can take a very small corpus (say 10k sentences) and reduce the development size and the number of tuning and backtranslation iterations, so training should be really fast (it won't learn anything meaningful though).
