### ISSUE TITLE
Step 7 unspervised_tuning problem with moses2

### ISSUE THREAD

**Issue by ningqiuyi** [artetxem/monoses#10]
Your system is very good, I am learning to use it, but now I have a problem! In step 7 unspervised_tuning, I can't find the moses2 file in the bin directory. Is the moses2  in train.py  is the bin/moses in the updated moses system? If not, can you send me a moses2 file?

**Comment by ningqiuyi** [comment]
Oh,just due to my carelessness,I have solved it! Thanks a lot.

**Comment by takkarparas** [comment]
ERROR: compile with bjam --with-cmph at /home/shweta/MONOSES/monoses/third-party/moses/scripts/generic/binarize4moses2.perl line 35.
Using SCRIPTS_ROOTDIR: /home/shweta/MONOSES/monoses/third-party/moses/scripts
Not executable: /home/shweta/MONOSES/monoses/third-party/moses/bin/moses2 at /home/shweta/MONOSES/monoses/third-party/moses/scripts/training/mert-moses.pl line 466.
Traceback (most recent call last):
  File "/home/shweta/anaconda3/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'MODEL-DIR15/tmpjq87_21y/mert/moses.ini' -> 'MODEL-DIR15/step7/src2trg.it1.moses.ini'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 478, in main
    unsupervised_tuning(args)
  File "train.py", line 366, in unsupervised_tuning
    shutil.move(args.tmp + '/mert/moses.ini', config[(src, trg)])
  File "/home/shweta/anaconda3/lib/python3.7/shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "/home/shweta/anaconda3/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/shweta/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:

I am still getting this error after replacing moses with moses2. @ningqiuyi can you please help me with this.
