### ISSUE TITLE
compiling Phrase2vec 

### ISSUE THREAD

**Issue by sevilaybayatli** [artetxem/monoses#13]
hello,

I did not know how to compile Phrase2vec, this site  https://github.com/artetxem/phrase2vec you pointed, but there is any instruction  how to install it, so because that I got these bash: /media/adminonur/bee/monoses/third-party/phrase2vec/word2vec: No such file or directory
head: cannot open 'MODEL-DIR/tmpk7yaqfp0/vocab-full.txt' for reading: No such file or directory
bash: /media/adminonur/bee/monoses/third-party/phrase2vec/word2vec: No such file or directory
bash: /media/adminonur/bee/monoses/third-party/phrase2vec/word2vec: No such file or directory
head: cannot open 'MODEL-DIR/tmpk7yaqfp0/vocab-full.txt' for reading: No such file or directory
bash: /media/adminonur/bee/monoses/third-party/phrase2vec/word2vec: No such file or directory

please could you point me?

**Comment by w4w4n78** [comment]
Hi, I'm encounter the same problem as described above, any solution?

**Comment by gitlost-murali** [comment]
Hope this is helpful for anyone who has the same issue.

Run `make`. This will generate the `word2vec` executable file.
