### ISSUE TITLE
Step 8: Probing Table:: Bucket full error

### ISSUE THREAD

**Issue by shefs0709** [artetxem/monoses#17]
Hey everyone,
I am trying to reproduce your result but can't get past step 7. I am using the WMT English-Polish language but facing error in step 8.
Attaching my error.
![IMG-20200807-WA0003](https://user-images.githubusercontent.com/44344241/89668784-fb233180-d8fb-11ea-92f5-7beaa3c76084.jpg)

Thank u in advance...

**Comment by catarinaferrei** [comment]
were you able to solve this? im having the same problem

**Comment by shefs0709** [comment]
Hi catarinaferrei
Increasing the RAM size works for me.
