### ISSUE TITLE
Segmentation fault: STEP 7 unsupervised_tuning

### ISSUE THREAD

**Issue by JiqiangLiu** [artetxem/monoses#3]
Hi, thank you for your great work. I run this code and encounter error, segmentation fault,  during STEP 7.
More specifically,   the error occurred in code is
https://github.com/artetxem/monoses/blob/c8549e0cf2830de44374a4560a8c81cedba8161d/train.py#L353

and part of log file is [log.txt](https://github.com/artetxem/monoses/files/2565068/log.txt)
Could you give some advice about this problem?  Thank you.

**Comment by 15091444119** [comment]
I got the same error.

**Comment by 15091444119** [comment]
> Hi, thank you for your great work. I run this code and encounter error, segmentation fault, during STEP 7.
> More specifically, the error occurred in code is
> [monoses/train.py](https://github.com/artetxem/monoses/blob/c8549e0cf2830de44374a4560a8c81cedba8161d/train.py#L353)
> 
> Line 353 in [c8549e0](/artetxem/monoses/commit/c8549e0cf2830de44374a4560a8c81cedba8161d)
> 
>  bash(quote(MOSES + '/scripts/training/mert-moses.pl') + 
> and part of log file is [log.txt](https://github.com/artetxem/monoses/files/2565068/log.txt)
> Could you give some advice about this problem? Thank you.

Hi, have you solve this problem?

**Comment by 15091444119** [comment]
> Hi, thank you for your great work. I run this code and encounter error, segmentation fault, during STEP 7.
> More specifically, the error occurred in code is
> [monoses/train.py](https://github.com/artetxem/monoses/blob/c8549e0cf2830de44374a4560a8c81cedba8161d/train.py#L353)
> 
> Line 353 in [c8549e0](/artetxem/monoses/commit/c8549e0cf2830de44374a4560a8c81cedba8161d)
> 
>  bash(quote(MOSES + '/scripts/training/mert-moses.pl') + 
> and part of log file is [log.txt](https://github.com/artetxem/monoses/files/2565068/log.txt)
> Could you give some advice about this problem? Thank you.

Hi, have you solved this problem?

**Comment by 15091444119** [comment]
@JiqiangLiu  Thanks anyway!

**Comment by JiqiangLiu** [comment]
Segmentation errors usually mean that the input may be problematic. You could check whether the input is wrong.

**Comment by artetxem** [comment]
This looks like a compilation issue with Moses. Make sure that Moses is properly compiled (e.g. moses2 should exist under bin).

**Comment by JiqiangLiu** [comment]
Recently, I solve the segmentation fault but during the translation by removing the special char '|' in the test data.
