### ISSUE TITLE
Can it run on gpu?

### ISSUE THREAD

**Issue by riktimmondal** [artetxem/monoses#4]
Hello,Truly appreciated with work.I am using a corpora with 10lakh sentences.In the "induce-phrase-table.py" file there is default option of using cuda,,but after checking gpu usage its 0 %.So pls can out clarify what does induce-phrase-table is actually doing ,or how can I increase traning speed.

Thanks a lot.

**Comment by artetxem** [comment]
It is possible to run that step on GPU but you should modify the code manually by adding the '--cuda' flag in the corresponding call from train.py.
