### ISSUE TITLE
Features are 0: Step 7 unsupervised_tuning

### ISSUE THREAD

**Issue by yvonnegitau** [artetxem/monoses#5]
@artetxem Great work on the project. I am trying to reproduce your results but cant get past step 7
I am using wmt14 news.2010 french and english text. After the first iteration of step 7 the features in the features list are all 0. Therefore throwing an error of Illegal division by zero at moses/scripts/training/mert-moses.pl line 1290

I have tried with other datasets but still getting the same error

**Comment by artetxem** [comment]
Looks like a duplicate of #3 . Make sure that Moses is properly compiled (e.g. moses2 should exist under bin).

**Comment by yvonnegitau** [comment]
Thanks for that. Used the binary file of moses and it worked
