### ISSUE TITLE
Compilation bug with moses2 (and my solution)

### ISSUE THREAD

**Issue by mayhewsw** [artetxem/monoses#6]
Hi, thanks for publishing this code -- just wanted to point out that I had issues with compiling moses2. These were strange compilation problems relating to HypothesisColl.h and an unordered set and whether or not to import it from boost or std. It turns out that since the version 4 release of Moses (which is used in this repo), they have rolled back changes in this file relating to this very issue. 

I finally fixed the problem by checking out the latest version of moses. (As of writing, that commit hash was: 187a75cb5596c8e4362c66c62de395e2b7d3a64a)

**Comment by artetxem** [comment]
Thanks for sharing!
