### ISSUE TITLE
the meaning of Phrase table

### ISSUE THREAD

**Issue by JiqiangLiu** [artetxem/monoses#8]
Hi, thanks for your great work. I noticed that , in the  step of Induce phrase-table,  the first score is direct phrase translation probability， the second is inverse phrase translation probability. However， moses 's phrases table is that the first is inverse phrase translation probability. the third is direct phrase translation probability.
Unfortunately, I am not familiar with statistical machine translation. I look forward to your reply.

**Comment by artetxem** [comment]
The order of the features in the phrase table is irrelevant as long as tuning is done consistently.
